baseURL = "https://www.johnbostanci.com/"
languageCode = "en-us"
title = "John Bostanci"
theme = "cactus"

[params]
colortheme = "white"
description = "John Bostanci is a PhD student in theoretical computer science at Columbia University, researching quantum computation, quantum cryptography, and algorithms for learning from quantum data."
